runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F2

env_variables:
  PROD: "corraborator-gcp-prod"

handlers:
# - url: /stylesheets
#   static_dir: stylesheets

# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

- url: /
  secure: always
  static_files: dist/corroborator-ui/index.html
  upload: dist/corroborator-ui/index.html

- url: /
  static_dir: dist/corroborator-ui/
